### ISSUE TITLE
http://www.etudes-francaises.net/dossiers/technologies.htm

### ISSUE THREAD

**Issue by peterkingalex** [esc/conda-zsh-completion#1]
Marie Lebert, 2008
[FR] Technologies et livre pour tous (PDF, 2008)

Du Projet Gutenberg en 1971 à l'Encyclopedia of Life en 2007, 38 étapes avec résumé et descriptif plus détaillé. Disponible aussi en version TXT.
[EN] Technology and books for all (PDF, 2008)

From Project Gutenberg in 1971 to the Encyclopedia of Life in 2007, 38 milestones, with an overview and an in-depth description. TXT version also available.
[EN] Booknology, with Marc Autret (PDF, 2009)
Voir aussi / See also:

[FR] Les mutations du livre (PDF et TXT, 2007)

[FR] Le livre numérique: chronologie (HTML, 2007)

[ES] El Proyecto Gutenberg (HTML, 2007)

[FR] Le Projet Gutenberg (TXT, 2008)

[EN] Project Gutenberg (TXT, 2008)

[Dossiers du NEF] / [NEF]

Copyright © 2008 Marie Lebert. Tous droits réservés / All rights reserved.

**Comment by esc** [comment]
Please don't spam.
