### ISSUE TITLE
Error when mistype subcommand

### ISSUE THREAD

**Issue by cgjosephlee** [esc/conda-zsh-completion#16]
`conda aa<TAB>` should return an error since no subcommand started with `aa`, but it comes a weird error and ruins the `$PROMT`.
```
$ conda aa<TAB>
$ conda aa_main_complete:202: permission denied:
_main_complete:202: permission denied:
conda       conda aa
No matches for: `conda commands'
```

**Comment by cgjosephlee** [comment]
Error here??
https://github.com/zsh-users/zsh/blob/master/Completion/Base/Core/_main_complete#L202

**Comment by piojanu** [comment]
I have it too, have you come up with work around?

**Comment by esc** [comment]
I can't reproduce this, and I don't think it is an issue with the conda-zsh-completion.

**Comment by drorata** [comment]
I also had this issue --- killing the terminal and restarting it solved the problem. For the time being.
