### ISSUE TITLE
How about a LICENSE file?

### ISSUE THREAD

**Issue by apjanke** [esc/conda-zsh-completion#18]
I know you declare the license [in the `_conda` source](https://github.com/esc/conda-zsh-completion/blob/846f06f742746430efa406c3fc49c61208988b88/_conda#L7), but how about adding a LICENSE file to make it easier for users to find, and so GitHub can automatically detect it and label your repo as so licensed?

**Comment by esc** [comment]
sure, PRs welcome!

**Comment by apjanke** [comment]
PR submitted! #20
