### ISSUE TITLE
Completions do not work at all for certain combinations of OS/conda/zsh/OMZ

### ISSUE THREAD

**Issue by chrissype** [esc/conda-zsh-completion#21]
I've successfully and happily made the completions work on an Ubuntu 18.04 box by following the installation instructions, however on my laptop the procedure does not work. I'm using Ubuntu 16.04, conda 4.6.14, zsh 5.1.1 and the latest oh-my-zsh (078f64dcf9c56f45d1d5e9e49dd5709baedc1386)

**Comment by esc** [comment]
@chrissype thank you for using the conda-zsh-completion - can you provide more information about what you did, what you expected, and what happens instead?

**Comment by chrissype** [comment]
`$ git clone https://github.com/esc/conda-zsh-completion
$ sudo mv conda-zsh-completion/_conda  /usr/share/zsh/functions/Completion/Zsh/
$ compinit conda`

Doing the exact same series of commands worked on the Ubuntu 18.04 machine, and tab completion subsequently works with both commands and environments, eg

`conda activate ba (+tab)`  completes to `conda activate base`

Trying the same thing on the 16.04 machine just tries to bring up completions based on the names of files in the current directory, while I was expecting it to work exactly the same.

**Comment by chrissype** [comment]
If you put the _conda completions file in the oh-my-zsh completions directory (`/home/ccg/.oh-my-zsh/completions`) and run compinit conda then completions work for 16.04, however if you put it in the Zsh one (`/usr/share/zsh/functions/Completion/Zsh`) then it does not, even though both are in $fpath.

This is not the case for the 18.04 versions.

**Comment by esc** [comment]
@chrissype thanks for following up on this and closing the issue!
