### ISSUE TITLE
`autoload -U compinit && compinit` has no effect unless put in the end of the file

### ISSUE THREAD

**Issue by GabrielAzevedoFerreiraQB** [esc/conda-zsh-completion#26]
I am using oh-my-zsh in a Mac. For me, the  way I found to make the plugin work was doing the following in the `.zshrc` file:
1) clone the repository on the oh-my-zsh plugin repository
```
git clone https://github.com/esc/conda-zsh-completion ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/conda-zsh-completion
```

2) Adding the conda-zsh-completion on the list of plugins
```
plugins=(git conda-zsh-completion) # this was, by default, plugins=(git)
```

3) Adding the following line in the *end of the file, below the line *`source $ZSH/oh-my-zsh.sh`:
```
autoload -U compinit && compinit 
```
---------------------

This was slightly different than (what I understood) the instructions said. 
The difference is that I purposely put the step 3 line after the sourcing of `oh-my-zsh.sh`. 
If I put step 3 line just below step 2 line it does not work (possibly the command gets overwriten in `oh-my-zsh.sh`...).

--------------------
I wonder why this happened in my machine and if my case is the rule or the exception.

In case it happens to at least some people, do you think it is worth adapting the readme to specifying the step 3 should be after `source $ZSH/oh-my-zsh.sh`?

thanks

**Comment by Huitzilo** [comment]
Thanks @GabrielAzevedoFerreiraQB for figuring this out! 

I think it would help adding a note to the installation instructions. Would have saved me 10 minutes today. Multiply this by 10 million conda users who also use oh-my-zsh and these completions, you save humanity 190.26 man-years! ;)

**Comment by esc** [comment]
@Huitzilo sure, pull-requests welcome. I don't use oh-my-zsh so. I'll have to trust you. 😉

**Comment by Huitzilo** [comment]
Pull request made.

**Comment by esc** [comment]
@Huitzilo thanks for submitting, it has been merged!

**Comment by esc** [comment]
Would it be reasonable to close this issue now?

**Comment by Huitzilo** [comment]
I guess so! Unless @GabrielAzevedoFerreiraQB has something to add?

**Comment by esc** [comment]
I think it is time to close this issue, I believe the issue has been addressed. Please feel free to re-open this PR or open another one should the issue resurface. Thanks!

**Comment by nathanjones4323** [comment]
Not sure if was just me, but these instructions were the most concise and helpful.

I didn't follow the documentation nearly as easily as this
