### ISSUE TITLE
source activate autocomplete

### ISSUE THREAD

**Issue by rth** [esc/conda-zsh-completion#3]
I was wondering how hard it would be extend this to support auto-completion for `source activate` (which would list the available conda environements).?

There is some discussion about it in https://github.com/conda/conda/issues/2595 and https://github.com/conda/conda/issues/822 suggesting that it might be more simply achievable with zsh than bash...

**Comment by esc** [comment]
pull-requests welcome

**Comment by esc** [comment]
;-)

**Comment by esc** [comment]
Newer versions of `conda` now have `activate` and `deactivate` which can be completed as of v0.6 of this completion as #11 has been merged.

**Comment by esc** [comment]
I presume this is the feature you wanted and am thus going to close this issue. Feel free to re-open with more details should this not suffice.
