### ISSUE TITLE
Inefficient env list calculation

### ISSUE THREAD

**Issue by Ewande** [esc/conda-zsh-completion#30]
The current implementation is a bit slow, if you look at it from the perspective of navigating in terminal:
https://github.com/esc/conda-zsh-completion/blob/4121e838c83fb84461b2c1332929ab34a26fbf62/_conda#L131
My benchmark (for 10 runs):
```
➜ bash -c "time for i in {1..10}; do conda info -e | sed '1,2d' | cut -f1 -d' ' >> /dev/null; done"

real	0m3.070s
user	0m2.467s
sys	0m0.594s
```

My proposed change:
```echo base && ls -1 ${${CONDA_EXE}%bin/conda}/envs && echo```
(echo at the end is not required but I wanted both implementations to create exactly the same output)
and benchmark (for 10 runs):
```
➜ bash -c "time for i in {1..10}; do (echo base && ls -1 ${${CONDA_EXE}%bin/conda}/envs && echo) >> /dev/null; done"

real	0m0.039s
user	0m0.013s
sys	0m0.021s
```

I've been using this replacement for over a year now for `conda activate` and I didn't have any issues.

I can create a PR if you think this change is reasonable.`

**Comment by nielstron** [comment]
This proposal does not cover environments in.a custom path if I see correctly? I mean environment that are created like `conda create ./custom_path`
